import Head from "next/head";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import Experience from "../components/Experience";
import Projects from "../components/Projects";
import SocialLinks from "../components/SocialLinks";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thomas | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <SocialLinks />
      <Experience />
      <Projects />
      <div className="lg:hidden">
        <Contact />
      </div>
    </div>
  );
}
