import Head from 'next/head'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import About from '../components/About'
import Experience from '../components/Experience'
import Projects from '../components/Projects'
import SocialLinks from "../components/SocialLinks"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Thomas | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <SocialLinks/>
      <About/>
      <Experience/>
    
      <Projects/>
    </div>
  )
}

